#!/bin/bash

# This pre-commit hook will prevent any commit by unvalid author name/email

CURRENT_NAME="$(git config user.name)"
CURRENT_EMAIL="$(git config user.email)"

# Enter git.name + git.email here
VALID_NAME=''
VALID_EMAIL=''

RED='\033[0;31m'
NC='\033[0m'

EXIT_STATUS=0

if [[ "${VALID_NAME}" != "${CURRENT_NAME}" ]]
then
    printf "${RED}Invalid username for commit.${NC}\n"
    EXIT_STATUS=1
fi

if [[ "${VALID_EMAIL}" != "${CURRENT_EMAIL}" ]]
then
    printf "${RED}Invalid user email for commit.${NC}\n"
    EXIT_STATUS=1
fi

exit ${EXIT_STATUS}
