list_sq = ["AI will be led by companies like Tesla.",
            "AI could be a risk for many workers.",
            "I am sure that social networks like facebook should use AI to counteract hatespeech comments.",
            "In the future, cars will be powered by alternative energy sources such as solar and wind power.",
            "In the future, there will be driverless cars.",
            "In the future, flying cars will be a common form of transport.",
            "In the future, hoverboards will be a common form of transport.",
            "In the future, the use of public transport will increase as it becomes more efficient and affordable.",
            "In the future, the number of people working from home will increase as technology advances.",
            "In the future, there will be more jobs in the service sector as automation increases.",
            "In the future, there will be more jobs in the green economy as we move away from fossil fuels.",
            "In the future, artificial intelligence will lead to the creation of new jobs in fields such as healthcare and finance.",
            "In the future, social media will be used more for business networking and less for personal use.",
            "In the future, there will be more regulation of social media to protect people's privacy.",
            "In the future, virtual reality will be used more for social interaction and entertainment.",
            "In the future, augmented reality will be used",
"We’ll see a diversity of new technologies aimed at both reducing and removing the world’s emissions – unleashing a wave of innovation to compare with the industrial and digital Revolutions of the past.",
"By 2025, quantum computing will have outgrown its infancy, and a first generation of commercial devices will be able tackle meaningful, real-world problems.",
"One major application of this new kind of computer will be the simulation of complex chemical reactions, a powerful tool that opens up new avenues in drug development.",
"Quantum chemistry calculations will also aid the design of novel materials with desired properties, for instance better catalysts for the automotive industry that curb emissions and help fight climate change.",
"By 2025, healthcare systems will adopt more preventative health approaches based on the developing science behind the health benefits of plant-rich, nutrient-dense diets.",
"This trend will be enabled by AI-powered and systems biology-based technology that exponentially grows our knowledge of the role of specific dietary phytonutrients in specific human health and functional outcomes.",
"After the pandemic of 2020, consumers will be more aware of the importance of their underlying health and will increasingly demand healthier food to help support their natural defences.",
"Engineering biology, machine learning and the sharing economy will establish a framework for decentralising the healthcare continuum, moving it from institutions to the individual.",
"Propelling this forward are advances in artificial intelligence and new supply chain delivery mechanisms, which require the real-time biological data that engineering biology will deliver as simple, low-cost diagnostic tests to individuals in every corner of the globe. As a result, morbidity, mortality and costs will decrease in acute conditions, such as infectious diseases, because only the most severe cases will need additional care.",
"Fewer infected people will leave their homes, dramatically altering disease epidemiology while decreasing the burden on healthcare systems.",
"Inextricable links between health, socio-economic status and quality of life will begin to loosen, and tensions that exist by equating health with access to healthcare institutions will dissipate.",
"From daily care to pandemics, these converging technologies will alter economic and social factors to relieve many pressures on the global human condition.",
"Construction will become a synchronized sequence of manufacturing processes, delivering control, change and production at scale. It will be a safer, faster and more cost-effective way to build the homes, offices, factories and other structures we need to thrive in cities and beyond.",
"While humanity will do everything possible to stop emitting more carbon into the atmosphere, it will also do everything it can in order to remove historic CO2 from the air permanently.",
"CO2 removal will be scaled up to the gigaton-level, and will become the responsible option for removing unavoidable emissions from the air. It will empower individuals to have a direct and climate-positive impact on the level of CO2 in the atmosphere. It will ultimately help to prevent global warming from reaching dangerous levels and give humanity the potential to reverse climate change.",
"AI is that new tool that will enable us to extract more insights at an unprecedented level from all the medical 'big data' that has never really been fully taken advantage of in the past. It will shift the world of medicine and how it is practiced.",
"The scientific machine learning that combines physics-based models with big data will lead to leaner designs, lower operating costs and ultimately clean, affordable energy for all.",
"The ability to monitor structural health in real-time and fix things before they break will result in safer, more resilient infrastructure and everything from wind farms to bridges and unmanned aerial vehicles being protected by a real-time digital twin.",
"Every surface on Earth carries hidden information that will prove essential for avoiding pandemic-related crises, both now and in the future.",
"Technology that accelerates our ability to rapidly sample, digitalize and interpret microbiome data will transform our understanding of how pathogens spread. Exposing this invisible microbiome data layer will identify genetic signatures that can predict when and where people and groups are shedding pathogens, which surfaces and environments present the highest transmission risk, and how these risks are impacted by our actions and change over time.",
"We are just scratching the surface of what microbiome data insights offer and will see this accelerate over the next five years. These insights will not only help us avoid and respond to pandemics, but will influence how we design, operate and clean environments like buildings, cars, subways and planes, in addition to how we support economic activity without sacrificing public health.",
"Over the next five years, carbon-heavy industries will use machine learning and AI technology to dramatically reduce their carbon footprint.",
"These efforts will be led by cross-functional teams representing the data, privacy and security interests within an organization.",
"The next five years will see profound improvements in addressing these challenges as entrepreneurs, the investment community and the world’s largest enterprise R&D organizations focus on developing and deploying solutions that will deliver tangible results.",
"With human rights groups like Amnesty International putting a spotlight on this issue, along with the rise of environmental, social and governance (ESG) investing and increased calls for stakeholder capitalism, we predict that there will be more progress in responsible investing in tech – especially in the venture capital space – in the coming years.",
"The Chinese government released a document in August 2021 stating that authorities will actively promote legislation in areas such as national security, technology innovation and anti-monopoly.",
"We predict that future regulations will be more targeted towards specific technologies, industries, use cases, risk profiles and affected communities.",
           "Another Pandemic might come in the future.",
           "There is going to be a lot of disappointed people.",
           "In the next months a lot of companies are going to have a challenging time.",
           "It'll perform very poorly very rapidly.",
           "Life is going to punch you in the gut.",
           "With all those researchers, scammers, and ordinary humans solving billions of puzzles just at the threshold of what AI can do, at some point the machines are going to pass us by.",
           "It’s 2022 and you’re still going to lose the argument.",
]

list_neg = ["Fewer infected people will leave their homes, dramatically altering disease epidemiology while decreasing the burden on healthcare systems.",
"Inextricable links between health, socio-economic status and quality of life will begin to loosen, and tensions that exist by equating health with access to healthcare institutions will dissipate.",
"From daily care to pandemics, these converging technologies will alter economic and social factors to relieve many pressures on the global human condition.",
"Construction will become a synchronized sequence of manufacturing processes, delivering control, change and production at scale. It will be a safer, faster and more cost-effective way to build the homes, offices, factories and other structures we need to thrive in cities and beyond.",
"While humanity will do everything possible to stop emitting more carbon into the atmosphere, it will also do everything it can in order to remove historic CO2 from the air permanently.",
"CO2 removal will be scaled up to the gigaton-level, and will become the responsible option for removing unavoidable emissions from the air. It will empower individuals to have a direct and climate-positive impact on the level of CO2 in the atmosphere. It will ultimately help to prevent global warming from reaching dangerous levels and give humanity the potential to reverse climate change.",
"AI is that new tool that will enable us to extract more insights at an unprecedented level from all the medical 'big data' that has never really been fully taken advantage of in the past. It will shift the world of medicine and how it is practiced.",
"The scientific machine learning that combines physics-based models with big data will lead to leaner designs, lower operating costs and ultimately clean, affordable energy for all.",
"The ability to monitor structural health in real-time and fix things before they break will result in safer, more resilient infrastructure and everything from wind farms to bridges and unmanned aerial vehicles being protected by a real-time digital twin.",
"Every surface on Earth carries hidden information that will prove essential for avoiding pandemic-related crises, both now and in the future.",
"Technology that accelerates our ability to rapidly sample, digitalize and interpret microbiome data will transform our understanding of how pathogens spread. Exposing this invisible microbiome data layer will identify genetic signatures that can predict when and where people and groups are shedding pathogens, which surfaces and environments present the highest transmission risk, and how these risks are impacted by our actions and change over time.",
"We are just scratching the surface of what microbiome data insights offer and will see this accelerate over the next five years. These insights will not only help us avoid and respond to pandemics, but will influence how we design, operate and clean environments like buildings, cars, subways and planes, in addition to how we support economic activity without sacrificing public health.",
"Over the next five years, carbon-heavy industries will use machine learning and AI technology to dramatically reduce their carbon footprint.",
"These efforts will be led by cross-functional teams representing the data, privacy and security interests within an organization.",
"The next five years will see profound improvements in addressing these challenges as entrepreneurs, the investment community and the world’s largest enterprise R&D organizations focus on developing and deploying solutions that will deliver tangible results.",
"With human rights groups like Amnesty International putting a spotlight on this issue, along with the rise of environmental, social and governance (ESG) investing and increased calls for stakeholder capitalism, we predict that there will be more progress in responsible investing in tech – especially in the venture capital space – in the coming years.",
"The Chinese government released a document in August 2021 stating that authorities will actively promote legislation in areas such as national security, technology innovation and anti-monopoly.",]